# Generated by Django 4.0.1 on 2022-01-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='track',
        ),
        migrations.AddField(
            model_name='annotation',
            name='track_album',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='annotation',
            name='track_artist',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='annotation',
            name='track_id',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='annotation',
            name='track_title',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='annotation',
            name='user_id',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
