# Generated by Django 4.0.1 on 2022-01-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_remove_annotation_track_annotation_track_album_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='track_album',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='track_artist',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='track_title',
        ),
        migrations.AddField(
            model_name='annotation',
            name='album',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='annotation',
            name='artist',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='annotation',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='track_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='user_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
