# Generated by Django 4.0.1 on 2022-01-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_remove_annotation_track_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='total_tracks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='track_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='mirex_mood',
            field=models.IntegerField(choices=[(1, 'Passionate'), (2, 'Cheerful'), (3, 'Bittersweet'), (4, 'Humorous'), (5, 'Tense')]),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='user_id',
            field=models.CharField(default='default_user', max_length=200),
        ),
    ]
